/** i18n strings — keys match legacy web `app/src/i18n/en.ts`. */
export const en = {
  appName: "Fix It IQ",
  tagline: "Car repair and parts marketplace",
  welcome: "Welcome",
  authSubtitle: "Sign in with Google, Apple, or your phone number.",
  continueWithGoogle: "Continue with Google",
  continueWithApple: "Continue with Apple",
  usePhoneInstead: "Use phone number instead",
  authSignInFailed: "Sign-in failed. Try again.",
  authFirebaseConfigHint:
    "Add EXPO_PUBLIC_FIREBASE_* keys from the Firebase console (same project as the API service account).",
  authGoogleClientHint:
    "Set EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID (Web client ID from Google Cloud / Firebase).",
  authExpoGoGoogleRedirectHint:
    "Expo Go: run `npx expo login`, set EXPO_PUBLIC_EXPO_PROJECT_FULL_NAME=@yourExpoUsername/fixit in .env, add Authorized redirect URI https://auth.expo.io/@yourExpoUsername/fixit to the Google Web client, restart Metro.",
  authGoogleNativeHint:
    "Native Google sign-in runs in development and release builds (`npx expo run:android` / `run:ios`), not in Expo Go.",
  enterPhoneHint: "Enter your WhatsApp number to get started",
  sendCode: "Send code on WhatsApp",
  otpHint: "Enter the 6-digit code",
  verify: "Verify",
  resend: "Resend",
  accountType: "I am a…",
  carOwner: "Car owner",
  shop: "Shop / Workshop",
  towingProvider: "Towing provider",
  continue: "Continue",
  myPosts: "My Posts",
  feed: "Requests",
  newPost: "New",
  inbox: "Inbox",
  profile: "Profile",
  myBids: "My bids",
  createPost: "Create post",
  editPost: "Edit request",
  viewPost: "View request",
  viewOnlyBanner: "This request has offers — delete and create a new one to change it.",
  postUpdated: "Changes saved",
  cannotEditPost: "This request can't be edited.",
  post: "Post",
  repair: "Repair",
  parts: "Spare parts",
  towing: "Towing",
  description: "Description",
  city: "City",
  district: "District",
  photos: "Photos",
  name: "Name",
  nameRequired: "Please enter your name",
  finishSetup: "Finish setup",
  placeBid: "Place bid",
  accept: "Accept",
  priceIqd: "Price (IQD)",
  message: "Message",
  logout: "Log out",
  language: "Language",
  towingLocation: "Your location",
  towTo: "Tow to (optional)",
  towToLabel: "Tow to",
  urgency: "Urgency",
  asap: "ASAP",
  withinHour: "Within the hour",
  shopName: "Shop name",
  /** Placeholder on hero — this is the public shop / business name (not your personal name). */
  shopNameOnHero: "Business name",
  /** Shop profile: contact card — saves to user account, not the banner title. */
  shopProfilePersonalName: "Your name (account)",
  /** Shop profile: one line under the hero title explaining it is the public workshop name. */
  shopHeroPublicNameHint: "Edit the text above to change the public workshop name.",
  servicesOffered: "Services offered",
  changeCoverPhoto: "Change cover photo",
  coverUploadFailed: "Could not upload the photo. Try again.",
  photoPermissionNeeded: "Allow photo access in Settings to pick a cover image.",
  createShop: "Create shop profile",
  devMockContinue: "Continue without SMS (mock number)",
  devOnlyNoSms: "Dev only — no real SMS/WhatsApp",
  devBypassSkipSend: "Enter bypass code only (skip send)",
  devApiHint:
    "API: {{url}} — on the OTP screen use DEV_OTP_BYPASS_CODE from api/.env.",
  devOtpHint:
    "Dev: use DEV_OTP_BYPASS_CODE from api/.env (no WhatsApp).",
  loading: "Loading…",
  search: "Search",
  noPosts: "No posts yet.",
  feedCouldNotLoad: "Could not load requests. Check connection and pull to retry.",
  feedForYou: "Requests",
  feedMoreSectionTitle: "More",
  feedMoreSectionHint: "Doesn't match your profile",
  feedMoreSectionHintNational: "Doesn't match your profile",
  feedMoreNationalTitle: "More",
  feedMoreEmpty: "No other requests right now.",
  feedNoMatchingPosts: "Nothing currently",
  carYearsInvalid: "Use years 1950–2035, “from” ≤ “to”, or leave fields blank.",
  pickDistrict: "Pick a district",
  pickCityFirst: "Choose your city above, then tap your district.",
  districtOtherHint:
    'You chose "Other" as city: pick the nearest district below (if the API has no "Other" rows yet, Baghdad areas are shown as a guide). Use Back to pick a listed city.',
  districtEmptyHelp:
    "No districts found for this city. Check your connection, ensure the API database is seeded, or go Back to change city.",
  addressOptional: "Address (optional)",
  changeCity: "Change city",
  back: "Back",
  services: "Services",
  carMakesHint: "Car makes (comma-separated)",
  repairCatsHint: "Repair categories (comma)",
  partsCatsHint: "Parts categories (comma)",
  partsNationwide: "Parts nationwide",
  deliveryAvailable: "Delivery available",
  english: "English",
  arabic: "العربية (عراق)",
  openInBrowser: "Create posts from the web app for now (camera & map).",
  inboxSoon: "Inbox — coming soon",
  paywallTitle: "Subscription",
  paywallSubtitle:
    "Subscribe to bid on requests, access the feed, and grow your workshop.",
  restorePurchases: "Restore purchases",
  paywallNoPackages:
    "No subscription packages loaded. Check RevenueCat & App Store Connect.",
  paywallWebHint:
    "In-app purchases run on iOS/Android builds. Use a device or simulator with RevenueCat configured.",
  subscribeNow: "Subscribe",
  chooseLanguageTitle: "Choose your language",
  chooseLanguageSubtitle: "You can change this anytime in Settings.",
  errorTitle: "Error",
  updateFailed: "Could not save. Try again.",
  editLocation: "Edit location",
  shopSubscriptionSection: "Subscription",
  shopSubscriptionActiveHint: "Your subscription is active.",
  shopSubscriptionInactiveHint: "Subscribe to bid on jobs and use the full shop feed.",
  shopSubscriptionManageHint:
    "Change plan, renew, or restore from the subscription sheet. Restore is also available below if you reinstall the app.",
  revenueCatKeysMissing:
    "Subscriptions need RevenueCat API keys in your mobile build (.env: EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID or _IOS). Rebuild the app after adding them.",
  allMakesSearchPlaceholder: "Search all makes…",
  openSubscriptionPlans: "Plans & pricing",
  subscriptionRestoreDone: "Purchases restored.",
  devLoginOwner: "Log in as dev owner",
  devLoginShop: "Log in as dev shop",
  devLoginHint: "Uses POST /api/v1/dev/session (no OTP). API needs DEV_ALLOW_SESSION_LOGIN.",
  addPhotos: "Add photos (optional, max 3)",
  postCreated: "Post sent",
  sendMessage: "Send",
  typeMessage: "Type a message…",
  noThreads: "No conversations yet.",
  chattingWith: "Chat",
  phone: "Phone",
  phoneWhatsApp: "Phone number / WhatsApp",
  phoneInvalidFormat: "Use +9647XXXXXXXXX (Iraq) or +90XXXXXXXXXX (Turkey).",
  phoneInUse: "This number is already linked to another account.",
  editName: "Edit name",
  save: "Save",
  saved: "Saved",
  shopInfo: "Shop info",
  shopProfile: "Workshop profile",
  bidsWon: "Bids won",
  rating: "Rating",
  noBidsYet: "No bids yet.",
  bidPending: "Pending",
  bidAccepted: "Accepted",
  bidWithdrawn: "Withdrawn",
  editBid: "Edit",
  withdrawBid: "Withdraw",
  hrsLeft: "h left",
  bidsCount: "bids",
  bestBid: "Best",
  deletePost: "Delete post?",
  delete: "Delete",
  cancel: "Cancel",
  closePhotoPreview: "Close photo",
  viewPhotoFullSize: "View full size",
  waitingForBids: "Waiting for bids…",
  newPostHint: "Need something else? Tap + to post",
  all: "All",
  bidSent: "Bid sent",
  new_: "New",
  distKm: "km",
  estimatedTime: "Estimated time",
  hours: "Hours",
  days: "Days",
  appointmentDate: "Appointment date",
  appointmentTime: "Appointment time",
  messageToCustomer: "Message to customer",
  submitBid: "Submit bid",
  canAdjust: "Can adjust after inspection",
  deliveryDate: "Delivery date",
  deliveryWindow: "Delivery window",
  whatDoYouOffer: "What do you offer?",
  step: "Step",
  of: "of",
  selectAll: "Select all that apply",
  carMakesYears: "Car makes & years",
  popularInIraq: "Popular in Iraq",
  yearRange: "Year range",
  from: "From",
  to: "To",
  repairCategories: "Repair categories",
  partsCategories: "Parts categories",
  shopLocation: "Shop location",
  shopAddress: "Shop address (optional)",
  serviceArea: "Your service area",
  serviceAreaHint: "Controls which requests appear in your feed",
  nationwide: "Show requests from all of Iraq",
  reviewConfirm: "Review & confirm",
  createMyShop: "Create my shop profile",
  notifications: "Notifications",
  address: "Address",
  privacyPolicy: "Privacy policy",
  termsOfService: "Terms of service",
  deleteAccount: "Delete account",
  deleteAccountConfirmTitle: "Delete your account?",
  deleteAccountConfirmMessage:
    "This permanently deletes your profile, shop (if any), posts, bids, and chat history from our servers, removes your Firebase sign-in (if used), and clears this device. You cannot undo this.",
  deleteAccountConfirmButton: "Delete permanently",
  deleteAccountFailed: "Could not delete your account. Try again.",
  carMakes: "Car makes",
  towing_: "Towing",
  delivery: "Delivery",
  on: "On",
  off: "Off",
  editCategories: "Edit",
  reviews: "Reviews",
  checkWhatsApp: "Check WhatsApp",
  sentTo: "Code sent to",
  enterCode: "Enter code",
  resendIn: "Resend in",
  conditionNew: "New",
  conditionUsed: "Used",
  yearOptional: "Year (optional)",
  priceRequired: "Price required",
  deliveryNeeded: "Delivery needed",
  towingNotes: "Notes (optional)",
  other: "Other",
  openChat: "Open chat",
  bidAcceptedSystem: "Bid accepted",
  yes: "Yes",
  no: "No",
  detectLocation: "Detect my location",
  carMake: "Car make (e.g. Toyota)",
  carModel: "Model (e.g. Camry)",
  catCars: "Cars",
  catElectrics: "Electrics",
  catPlumbing: "Plumbing",
  catMetal: "Metal",
  catWood: "Wood",
  chooseCategoryTitle: "What's your specialty?",
  chooseCategorySubtitle: "You can't change this after setup.",
  serviceJob: "Service",
  serviceSupplies: "Supplies",
  yourCategory: "Category",
  requestTitle: "Request title",
  requestTitleHint: "e.g. Fix AC in living room",
  deliveryPreferred: "Delivery preferred?",
  chooseCity: "Choose city",
} as const;

export const arIq: Record<keyof typeof en, string> = {
  appName: "صلّحها",
  tagline: "سوق إصلاح السيارات وقطع الغيار",
  welcome: "أهلاً وسهلاً",
  authSubtitle: "سجّل الدخول بجوجل أو آبل أو رقم الهاتف.",
  continueWithGoogle: "المتابعة مع Google",
  continueWithApple: "المتابعة مع Apple",
  usePhoneInstead: "استخدام رقم الهاتف",
  authSignInFailed: "فشل تسجيل الدخول. حاول مرة ثانية.",
  authFirebaseConfigHint:
    "أضف مفاتيح EXPO_PUBLIC_FIREBASE_* من Firebase (نفس مشروع الـ API).",
  authGoogleClientHint:
    "عيّن EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID (معرّف عميل الويب من Google / Firebase).",
  authExpoGoGoogleRedirectHint:
    "Expo Go: نفّذ `npx expo login`، عيّن EXPO_PUBLIC_EXPO_PROJECT_FULL_NAME=@اسمك/fixit في .env، وأضف رابط إعادة التوجيه https://auth.expo.io/@اسمك/fixit في عميل Google للويب، ثم أعد تشغيل Metro.",
  authGoogleNativeHint:
    "تسجيل Google الأصلي يعمل في بنية التطوير والإصدار (`npx expo run:android` أو `run:ios`) وليس داخل Expo Go.",
  enterPhoneHint: "ادخل رقم الواتساب حتى نرسللك الكود",
  sendCode: "إرسال الكود عبر الواتساب",
  otpHint: "ادخل الكود المكوّن من 6 أرقام",
  verify: "تحقق",
  resend: "إعادة الإرسال",
  accountType: "أنا…",
  carOwner: "صاحب سيارة",
  shop: "ورشة / محل",
  towingProvider: "مزود خدمة السحب",
  continue: "تابع",
  myPosts: "طلباتي",
  feed: "الطلبات",
  newPost: "جديد",
  inbox: "الرسائل",
  profile: "الحساب",
  myBids: "عروضي",
  createPost: "إنشاء طلب",
  editPost: "تعديل الطلب",
  viewPost: "عرض الطلب",
  viewOnlyBanner: "هذا الطلب عليه عروض — احذفه وأنشئ طلبًا جديدًا إذا تريد تغييره.",
  postUpdated: "تم حفظ التغييرات",
  cannotEditPost: "لا يمكن تعديل هذا الطلب.",
  post: "نشر",
  repair: "إصلاح",
  parts: "قطع غيار",
  towing: "سحب",
  description: "الوصف",
  city: "المحافظة",
  district: "المنطقة",
  photos: "الصور",
  name: "الاسم",
  nameRequired: "الرجاء إدخال الاسم",
  finishSetup: "إنهاء الإعداد",
  placeBid: "أرسل عرض",
  accept: "اقبل",
  priceIqd: "السعر (د.ع)",
  message: "الرسالة",
  logout: "تسجيل الخروج",
  language: "اللغة",
  towingLocation: "موقعك",
  towTo: "السحب إلى (اختياري)",
  towToLabel: "السحب إلى",
  urgency: "الأولوية",
  asap: "بسرعة",
  withinHour: "خلال ساعة",
  shopName: "اسم الورشة",
  shopNameOnHero: "اسم النشاط التجاري",
  shopProfilePersonalName: "اسمك الشخصي (الحساب)",
  shopHeroPublicNameHint: "عدّل النص أعلاه لتغيير اسم الورشة الظاهر للجميع.",
  servicesOffered: "الخدمات المقدّمة",
  changeCoverPhoto: "تغيير صورة الغلاف",
  coverUploadFailed: "تعذّر رفع الصورة. جرّب مرة ثانية.",
  photoPermissionNeeded: "فعّل صلاحية الصور من الإعدادات لاختيار صورة الغلاف.",
  createShop: "إنشاء ملف الورشة",
  devMockContinue: "تابع بدون SMS (رقم تجريبي)",
  devOnlyNoSms: "وضع التطوير فقط — بدون SMS أو واتساب",
  devBypassSkipSend: "إدخال رمز التجاوز فقط (تخطي الإرسال)",
  devApiHint:
    "الخادم: {{url}} — في شاشة الرمز استخدم DEV_OTP_BYPASS_CODE من api/.env.",
  devOtpHint: "تطوير: استخدم DEV_OTP_BYPASS_CODE من api/.env",
  loading: "جاري التحميل…",
  search: "بحث",
  noPosts: "لا توجد طلبات بعد.",
  feedCouldNotLoad: "تعذّر تحميل الطلبات. تحقق من الاتصال واسحب للتحديث.",
  feedForYou: "الطلبات",
  feedMoreSectionTitle: "المزيد",
  feedMoreSectionHint: "لا يطابق ملف الورشة",
  feedMoreSectionHintNational: "لا يطابق ملف الورشة",
  feedMoreNationalTitle: "المزيد",
  feedMoreEmpty: "لا توجد طلبات أخرى حالياً.",
  feedNoMatchingPosts: "لا شيء حالياً",
  carYearsInvalid: "أدخل سنوات بين 1950 و2035، «من» أصغر أو يساوي «إلى»، أو اترك الحقلين فارغين.",
  pickDistrict: "اختر المنطقة",
  pickCityFirst: "اختر المحافظة أعلاه، ثم اضغط منطقتك.",
  districtOtherHint:
    'اخترت "أخرى": اختر أقرب منطقة أدناه (إن لم تُحمَّل مناطق لـ أخرى قد تُعرض مناطق بغداد). رجوع لتغيير المدينة.',
  districtEmptyHelp:
    "لا توجد مناطق لهذه المدينة. تحقق من الاتصال وتأكد من تهيئة قاعدة البيانات، أو ارجع لتغيير المدينة.",
  addressOptional: "العنوان (اختياري)",
  changeCity: "تغيير المدينة",
  back: "رجوع",
  services: "الخدمات",
  carMakesHint: "الماركات (مفصولة بفاصلة)",
  repairCatsHint: "فئات الإصلاح (فاصلة)",
  partsCatsHint: "فئات القطع (فاصلة)",
  partsNationwide: "قطع لجميع المحافظات",
  deliveryAvailable: "توصيل متاح",
  english: "English",
  arabic: "العربية (عراق)",
  openInBrowser: "أنشئ الطلبات من نسخة الويب حالياً (الكاميرا والخريطة).",
  inboxSoon: "الرسائل — قريباً",
  paywallTitle: "الاشتراك",
  paywallSubtitle:
    "اشترك لإرسال العروض على الطلبات والوصول للطلبات وتنمية الورشة.",
  restorePurchases: "استعادة المشتريات",
  paywallNoPackages:
    "لم تُحمَّل باقات الاشتراك. تحقق من RevenueCat ومتجر التطبيقات.",
  paywallWebHint:
    "المشتريات داخل التطبيق تعمل على iOS/Android. استخدم جهازاً أو محاكياً مع إعداد RevenueCat.",
  subscribeNow: "اشترك",
  chooseLanguageTitle: "اختر اللغة",
  chooseLanguageSubtitle: "تقدر تغيّرها لاحقاً من الإعدادات.",
  errorTitle: "خطأ",
  updateFailed: "ما نقدر نحفظ. جرّب مرة ثانية.",
  editLocation: "تعديل الموقع",
  shopSubscriptionSection: "الاشتراك",
  shopSubscriptionActiveHint: "اشتراكك مفعّل.",
  shopSubscriptionManageHint:
    "غيّر الخطة أو جدّد أو استعد من نافذة الاشتراك. «استعادة المشتريات» متاحة أيضاً إذا أعدت تثبيت التطبيق.",
  revenueCatKeysMissing:
    "الاشتراكات تحتاج مفاتيح RevenueCat في بناء التطبيق (.env: EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID أو _IOS). أعد بناء التطبيق بعد إضافتها.",
  allMakesSearchPlaceholder: "ابحث عن كل الماركات…",
  shopSubscriptionInactiveHint:
    "اشترك حتى تقدر تزايد على الطلبات وتشوف الخلاصة كاملة.",
  openSubscriptionPlans: "الباقات والأسعار",
  subscriptionRestoreDone: "تمت استعادة المشتريات.",
  devLoginOwner: "دخول كصاحب سيارة (تجربة)",
  devLoginShop: "دخول كورشة (تجربة)",
  devLoginHint: "يستخدم /api/v1/dev/session بدون OTP. فعّل DEV_ALLOW_SESSION_LOGIN في الـ API.",
  addPhotos: "إضافة صور (اختياري، حتى 3)",
  postCreated: "تم إرسال الطلب",
  sendMessage: "إرسال",
  typeMessage: "اكتب رسالة…",
  noThreads: "لا محادثات بعد.",
  chattingWith: "محادثة",
  phone: "رقم الهاتف",
  phoneWhatsApp: "رقم الهاتف / واتساب",
  phoneInvalidFormat: "استخدم +9647XXXXXXXXX (العراق) أو +90XXXXXXXXXX (تركيا).",
  phoneInUse: "هذا الرقم مربوط بحساب آخر.",
  editName: "تعديل الاسم",
  save: "حفظ",
  saved: "تم الحفظ",
  shopInfo: "معلومات الورشة",
  shopProfile: "ملف الورشة",
  bidsWon: "عروض مقبولة",
  rating: "التقييم",
  noBidsYet: "لا توجد عروض بعد.",
  bidPending: "بانتظار",
  bidAccepted: "مقبول",
  bidWithdrawn: "ملغي",
  editBid: "تعديل",
  withdrawBid: "سحب",
  hrsLeft: "س متبقية",
  bidsCount: "عروض",
  bestBid: "الأفضل",
  deletePost: "حذف الطلب؟",
  delete: "حذف",
  cancel: "إلغاء",
  closePhotoPreview: "إغلاق الصورة",
  viewPhotoFullSize: "عرض بالحجم الكامل",
  waitingForBids: "بانتظار العروض…",
  newPostHint: "تريد شي ثاني؟ اضغط + لإنشاء طلب",
  all: "الكل",
  bidSent: "تم الإرسال",
  new_: "جديد",
  distKm: "كم",
  estimatedTime: "الوقت التقديري",
  hours: "ساعات",
  days: "أيام",
  appointmentDate: "تاريخ الموعد",
  appointmentTime: "وقت الموعد",
  messageToCustomer: "رسالة للعميل",
  submitBid: "إرسال العرض",
  canAdjust: "يمكن التعديل بعد الفحص",
  deliveryDate: "تاريخ التوصيل",
  deliveryWindow: "فترة التوصيل",
  whatDoYouOffer: "شنو تقدم؟",
  step: "الخطوة",
  of: "من",
  selectAll: "اختر كل ما ينطبق عليك",
  carMakesYears: "الماركات والسنوات",
  popularInIraq: "الأكثر انتشاراً في العراق",
  yearRange: "نطاق السنوات",
  from: "من",
  to: "إلى",
  repairCategories: "فئات الإصلاح",
  partsCategories: "فئات قطع الغيار",
  shopLocation: "موقع الورشة",
  shopAddress: "عنوان الورشة (اختياري)",
  serviceArea: "نطاق الخدمة",
  serviceAreaHint: "يتحكم بالطلبات التي تظهر لك",
  nationwide: "طلبات من جميع أنحاء العراق",
  reviewConfirm: "مراجعة وتأكيد",
  createMyShop: "إنشاء ملف ورشتي",
  notifications: "الإشعارات",
  address: "العنوان",
  privacyPolicy: "سياسة الخصوصية",
  termsOfService: "شروط الخدمة",
  deleteAccount: "حذف الحساب",
  deleteAccountConfirmTitle: "حذف الحساب؟",
  deleteAccountConfirmMessage:
    "هذا يحذف نهائياً ملفك والورشة (إن وجدت) والطلبات والعروض والمحادثات من خوادمنا، ويزيل تسجيل Firebase (إن استُخدم)، ويمسح بيانات الجهاز. ما يمكن التراجع عنه.",
  deleteAccountConfirmButton: "حذف نهائي",
  deleteAccountFailed: "ما قدرنا نحذف الحساب. جرّب مرة ثانية.",
  carMakes: "الماركات",
  towing_: "سحب",
  delivery: "توصيل",
  on: "مفعل",
  off: "معطل",
  editCategories: "تعديل",
  reviews: "مراجعات",
  checkWhatsApp: "تحقق من الواتساب",
  sentTo: "الكود أُرسل إلى",
  enterCode: "أدخل الرمز",
  resendIn: "إعادة الإرسال خلال",
  conditionNew: "جديد",
  conditionUsed: "مستعمل",
  yearOptional: "السنة (اختياري)",
  priceRequired: "السعر مطلوب",
  deliveryNeeded: "هل تحتاج توصيل؟",
  towingNotes: "ملاحظات (اختياري)",
  other: "أخرى",
  openChat: "فتح المحادثة",
  bidAcceptedSystem: "تم قبول العرض",
  yes: "نعم",
  no: "لا",
  detectLocation: "تحديد موقعي",
  carMake: "الماركة (مثال: تويوتا)",
  carModel: "الموديل (مثال: كامري)",
  catCars: "سيارات",
  catElectrics: "كهرباء",
  catPlumbing: "صحية",
  catMetal: "حدادة",
  catWood: "نجارة",
  chooseCategoryTitle: "ما هو تخصصك؟",
  chooseCategorySubtitle: "لا يمكن تغييرها بعد الإعداد.",
  serviceJob: "خدمة",
  serviceSupplies: "مستلزمات",
  yourCategory: "التصنيف",
  requestTitle: "عنوان الطلب",
  requestTitleHint: "مثال: إصلاح مكيف غرفة المعيشة",
  deliveryPreferred: "هل تحتاج توصيل؟",
  chooseCity: "اختر المحافظة",
};

export type LocaleId = "en" | "ar-iq";

export type StringKey = keyof typeof en;
